name: ci

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.25.x"
          cache: true

      - name: Go build
        run: |
          go build -v ./...

      - name: Run govulncheck
        uses: golang/govulncheck-action@v1
        with:
          go-version-input: "1.25.x"

      - name: GoReleaser Build Check
        uses: goreleaser/goreleaser-action@v7
        with:
          distribution: goreleaser
          version: latest
          args: build --snapshot --clean

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: latest

      - name: Go fmt (check)
        run: |
          test -z "$(gofmt -l .)"

      - name: Go test
        run: |
          go test -coverprofile=coverage.txt -covermode=atomic ./...

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          file: ./coverage.txt
          fail_ci_if_error: false

      - name: Go vet
        run: |
          go vet ./...

      - name: CLI smoke
        run: |
          chmod +x scripts/cli-smoke.sh
          scripts/cli-smoke.sh

